name: ldm
channels:
  - pytorch
  - nvidia
  - defaults

dependencies:
  - python=3.10
  - pip
  - pytorch=2.11.*
  - torchvision=0.26.*
  - torchaudio=2.11.*
  - pytorch-cuda=12.8
  - numpy=1.24.*
  - pip:
    - albumentations==1.4.18
    - opencv-python-headless==4.10.0.84
    - imageio==2.36.0
    - imageio-ffmpeg==0.5.1
    - omegaconf==2.3.0
    - einops==0.8.0
    - pytorch-lightning==1.9.5
    - torch-fidelity==0.3.0
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e .
